{"hierarchy":{"paths":[["doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess","doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess"]]},"abstract":[{"type":"text","text":"An error related to running an external process."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdgexternalprocess\/externalprocess\/error"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error"},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/foundationError(_:)","doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/processError(code:output:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/presentableDescription()"]},{"title":"Default Implementations","identifiers":["doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/CustomStringConvertible-Implementations","doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/Error-Implementations","doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/LocalizedError-Implementations","doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/PresentableError-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/SDGExternalProcess\/10Foundation14LocalizedErrorP","doc:\/\/SDGExternalProcess\/15SDGLocalization16PresentableErrorP","doc:\/\/SDGExternalProcess\/s23CustomStringConvertibleP","doc:\/\/SDGExternalProcess\/s5ErrorP","doc:\/\/SDGExternalProcess\/s8SendableP"]}],"metadata":{"title":"ExternalProcess.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"roleHeading":"Enumeration","modules":[{"name":"SDGExternalProcess"}],"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"extendedModule":"SDGExternalProcess","externalID":"s:18SDGExternalProcess08ExternalB0V5ErrorO","role":"symbol"},"references":{"doc://SDGExternalProcess/s8SendableP":{"identifier":"doc:\/\/SDGExternalProcess\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess/Error/processError(code:output:)":{"identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/processError(code:output:)","abstract":[{"text":"The external process exited with an error.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"processError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"url":"\/documentation\/sdgexternalprocess\/externalprocess\/error\/processerror(code:output:)","title":"ExternalProcess.Error.processError(code:output:)","type":"topic"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess/Error/PresentableError-Implementations":{"url":"\/documentation\/sdgexternalprocess\/externalprocess\/error\/presentableerror-implementations","kind":"article","title":"PresentableError Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/PresentableError-Implementations","type":"topic"},"doc://SDGExternalProcess/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/SDGExternalProcess\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess/Error/CustomStringConvertible-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","title":"CustomStringConvertible Implementations","type":"topic","identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/CustomStringConvertible-Implementations","url":"\/documentation\/sdgexternalprocess\/externalprocess\/error\/customstringconvertible-implementations"},"doc://SDGExternalProcess/documentation/SDGExternalProcess":{"abstract":[{"text":"Tools for running external processes and shell commands.","type":"text"}],"title":"SDGExternalProcess","type":"topic","role":"collection","url":"\/documentation\/sdgexternalprocess","identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess","kind":"symbol"},"doc://SDGExternalProcess/s5ErrorP":{"identifier":"doc:\/\/SDGExternalProcess\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess":{"url":"\/documentation\/sdgexternalprocess\/externalprocess","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExternalProcess"}],"identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExternalProcess"}],"abstract":[{"type":"text","text":"An external process."}],"role":"symbol","kind":"symbol","title":"ExternalProcess"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess/Error/Error-Implementations":{"url":"\/documentation\/sdgexternalprocess\/externalprocess\/error\/error-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/Error-Implementations","title":"Error Implementations","type":"topic","role":"collectionGroup"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess/Error/presentableDescription()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentableDescription"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SDGText12StrictStringV","text":"StrictString"}],"identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/presentableDescription()","title":"presentableDescription()","url":"\/documentation\/sdgexternalprocess\/externalprocess\/error\/presentabledescription()","type":"topic","abstract":[],"kind":"symbol","role":"symbol"},"doc://SDGExternalProcess/15SDGLocalization16PresentableErrorP":{"identifier":"doc:\/\/SDGExternalProcess\/15SDGLocalization16PresentableErrorP","title":"SDGLocalization.PresentableError","type":"unresolvable"},"doc://SDGExternalProcess/s23CustomStringConvertibleP":{"identifier":"doc:\/\/SDGExternalProcess\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess/Error/LocalizedError-Implementations":{"type":"topic","kind":"article","title":"LocalizedError Implementations","url":"\/documentation\/sdgexternalprocess\/externalprocess\/error\/localizederror-implementations","abstract":[],"identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/LocalizedError-Implementations","role":"collectionGroup"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess/Error":{"url":"\/documentation\/sdgexternalprocess\/externalprocess\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[{"type":"text","text":"An error related to running an external process."}],"role":"symbol","kind":"symbol","title":"ExternalProcess.Error"},"doc://SDGExternalProcess/documentation/SDGExternalProcess/ExternalProcess/Error/foundationError(_:)":{"identifier":"doc:\/\/SDGExternalProcess\/documentation\/SDGExternalProcess\/ExternalProcess\/Error\/foundationError(_:)","abstract":[{"type":"text","text":"Foundation encountered an error."}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"foundationError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/sdgexternalprocess\/externalprocess\/error\/foundationerror(_:)","title":"ExternalProcess.Error.foundationError(_:)","type":"topic"}}}